# cr_embed_resource — generate a .cpp that .incbin's a binary file with a
# predictable C++ symbol, and append that .cpp to the target's sources.
#
# Usage:
#   cr_embed_resource(TARGET CameraReplace
#                     NAME   adb_exe          # -> cr::resources::adb_exe()
#                     FILE   "${ADB_EXE_PATH}"
#                     OUT_NAME "adb.exe")     # filename when extracted to disk
#
# If FILE does not exist at configure time, an empty placeholder is embedded
# so the build still succeeds (useful during bootstrap). A warning is printed.
# Changing FILE after configure is detected because we re-run on reconfigure
# and the generated .cpp carries the file's path literal.

function(cr_embed_resource)
    set(options)
    set(one_value_args TARGET NAME FILE OUT_NAME)
    set(multi_value_args)
    cmake_parse_arguments(CRE "${options}" "${one_value_args}"
                          "${multi_value_args}" ${ARGN})

    if(NOT CRE_TARGET OR NOT CRE_NAME OR NOT CRE_FILE)
        message(FATAL_ERROR "cr_embed_resource: TARGET, NAME, FILE are required")
    endif()
    if(NOT CRE_OUT_NAME)
        get_filename_component(CRE_OUT_NAME "${CRE_FILE}" NAME)
    endif()

    set(_gen_dir "${CMAKE_BINARY_DIR}/embed")
    file(MAKE_DIRECTORY "${_gen_dir}")
    set(_gen_cpp "${_gen_dir}/${CRE_NAME}.cpp")

    # Resolve to an absolute, forward-slashed path — the assembler's .incbin
    # directive wants that on Windows.
    set(_missing FALSE)
    if(EXISTS "${CRE_FILE}")
        file(REAL_PATH "${CRE_FILE}" _abs)
        file(SIZE "${_abs}" _plain_size)
        set(_seed_literal "0ull")
        set(_encrypted_literal "false")
        set(_incbin "${_abs}")
    else()
        set(_missing TRUE)
        set(_plain_size 0)
        set(_seed_literal "0ull")
        set(_encrypted_literal "false")
        message(WARNING
            "cr_embed_resource: file missing for '${CRE_NAME}' (${CRE_FILE}). "
            "Embedding empty placeholder; rebuild once it exists.")
        # Still need *some* path the assembler can open at build time.
        set(_placeholder "${_gen_dir}/${CRE_NAME}.placeholder")
        file(WRITE "${_placeholder}" "")
        set(_incbin "${_placeholder}")
    endif()

    # Pass the path through a single-quoted string at assembler time.
    file(TO_CMAKE_PATH "${_incbin}" _incbin_asm)
    string(REPLACE "\\" "/" _incbin_asm "${_incbin_asm}")

    # Write the generator .cpp. It carries an `asm(.incbin ...)` block plus an
    # accessor in the cr::resources namespace so the rest of the app never
    # touches the raw `_binary_*_*` symbols.
    file(WRITE "${_gen_cpp}" "\
// Auto-generated by cr_embed_resource — do not edit.
// Embeds plain payload '${CRE_FILE}' as resource '${CRE_NAME}'.

#include <cstddef>
#include \"resources/Resources.h\"

extern \"C\" {
extern const unsigned char _binary_${CRE_NAME}_start[];
extern const unsigned char _binary_${CRE_NAME}_end[];
}

asm(
\"   .section .rodata                                \\n\"
\"   .global _binary_${CRE_NAME}_start               \\n\"
\"   .global _binary_${CRE_NAME}_end                 \\n\"
\"   .p2align 4                                      \\n\"
\"_binary_${CRE_NAME}_start:                         \\n\"
\"   .incbin \\\"${_incbin_asm}\\\"                  \\n\"
\"_binary_${CRE_NAME}_end:                           \\n\"
);

namespace cr::resources {
Blob ${CRE_NAME}() noexcept {
    return Blob{
        _binary_${CRE_NAME}_start,
        static_cast<std::size_t>(${_plain_size}),
        static_cast<std::size_t>(_binary_${CRE_NAME}_end - _binary_${CRE_NAME}_start),
        ${_seed_literal},
        ${_encrypted_literal},
        \"\",
    };
}
}  // namespace cr::resources
")

    target_sources(${CRE_TARGET} PRIVATE "${_gen_cpp}")
    if(NOT _missing)
        set_source_files_properties("${_gen_cpp}" PROPERTIES
            OBJECT_DEPENDS "${_enc}")
    endif()

    # Re-run CMake (and regenerate) if the source blob changes on disk.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CRE_FILE}")
endfunction()
